# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
 - job: waitForValidation
   displayName: WAIT FOR EXTERNAL VALIDATION
   pool: server
   timeoutInMinutes: 2880 # job times out in 2 days
   steps:
    - task: ManualValidation@0
      timeoutInMinutes: 2880 # task times out in 2 day
      displayName:  MANUAL INTERVENTION
      inputs:
        notifyUsers: |
          raghu.vamsi@disys.com
        instructions: 'Please validate the deployment'
        onTimeout: 'reject'
    
 - job: Deployment
   displayName: Terraform Deployment
   dependsOn: waitForValidation
   steps:
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'